name: CI
on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install HatSploit
        run: sudo pip3 install .
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install HatSploit
        run: sudo pip3 install .
